"""Migrate Notes

Revision ID: 071d3cc6fc2c
Revises: ffdc0a98111c
Create Date: 2022-07-15 17:17:14.009369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071d3cc6fc2c'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
