"""Change Note body param back to original

Revision ID: 382f511e65d6
Revises: 7fb1c8b056c5
Create Date: 2022-07-18 17:12:43.363838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382f511e65d6'
down_revision = '7fb1c8b056c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('body', sa.Text(), nullable=False))
    op.drop_column('notes', 'content_body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content_body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'body')
    # ### end Alembic commands ###
