"""Fix Note body param

Revision ID: 7fb1c8b056c5
Revises: b50fa121cdaa
Create Date: 2022-07-18 17:06:32.456127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb1c8b056c5'
down_revision = 'b50fa121cdaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content_body', sa.Text(), nullable=False))
    op.drop_column('notes', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'content_body')
    # ### end Alembic commands ###
